server:
  port: 9001

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.82.217:3306/my_class?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: HJC916924
  mvc:
    servlet:
      load-on-startup: 1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.paperfly.entity
  global-config:
    db-config:
      id-type: id_worker
logging:
  level:
    com.paperlfy.mapper: debug
