server:
  port: 9101

spring:
  servlet:
    multipart:
      max-file-size: 1000000000
      max-request-size: 2000000000
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_class?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: HJC916924
  mvc:
    servlet:
      load-on-startup: 1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.paperfly.classUtils.entity
  global-config:
    db-config:
      id-type: AUTO
logging:
  level:
    com.paperlfy.mapper: debug